Predict on the given model, produce output graphs, and calcuate evaluation metrics.

# Input parameters here

In [1]:
# # PARAMETERS # # 
BASE_DIR = '/content/drive/My Drive/CS230_FinalReport/' # your base directory
EXP_TYPE = 'with_physicsinputs'

MASK_VALUE = 999.
if EXP_TYPE == 'with_physicsinputs': NUM_INPUT_FEATS = 42
if EXP_TYPE == 'without_physicsinputs': NUM_INPUT_FEATS = 34
NUM_OUTPUT_FEATS = 2
MODEL_FILENAME = '/content/drive/My Drive/CS230_FinalReport/models/' + EXP_TYPE + '_lstm_stepclass' # where you want to save the model to
SEED = 43
# # # # # # # # # # 

# Load libraries and other set up

In [2]:
from tensorflow import keras
import numpy as np
import os

In [3]:
# Mount Drive to access data.
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
# Set the random seed
keras.utils.set_random_seed(SEED)

In [5]:
# Load in data to predict on (dev or test sets).
datadir = os.path.join(BASE_DIR, 'data', 'processed', 'normalized')

X_test = np.load(file=os.path.join(datadir, EXP_TYPE, 'X_test_norm.npy'), allow_pickle=True)
Y_test = np.load(file=os.path.join(datadir, EXP_TYPE, 'Y_test_stepclass.npy'), allow_pickle=True)

# Gather predictions for later visualization and analysis

In [6]:
# Load saved model.
saved_model = keras.models.load_model(MODEL_FILENAME, compile = False)

# Gather all predictions on test set using the saved model.
preds = saved_model.predict(X_test)

# Save the preds.
predsdir = os.path.join(MODEL_FILENAME, 'testset_predictions.npy')
np.save(predsdir, preds)


26/26 [==============================] - 6s 11ms/step


In [7]:
preds.shape

(805, 67, 2)

In [8]:
preds[0,:,1]

array([9.9999976e-01, 9.9999833e-01, 9.9999917e-01, 9.9999928e-01,
       9.9999499e-01, 9.9999928e-01, 9.9998915e-01, 9.9994969e-01,
       9.9559033e-01, 6.6094939e-04, 4.7267178e-05, 7.7620571e-06,
       4.1484614e-06, 2.1089227e-06, 9.6838585e-07, 2.8230340e-07,
       1.3917045e-07, 6.5984878e-08, 4.2399083e-08, 1.1210734e-07,
       2.1673502e-07, 2.6340032e-07, 3.9934702e-07, 2.9663005e-07,
       1.4983074e-07, 1.5193210e-07, 1.0938011e-07, 8.4359890e-08,
       7.1411120e-07, 7.2396060e-06, 9.5966425e-06, 8.0657287e-07,
       1.5958990e-01, 9.9994934e-01, 9.9999762e-01, 9.9999881e-01,
       9.9999952e-01, 9.9999952e-01, 9.9999988e-01, 9.9999928e-01,
       9.9999869e-01, 7.1429795e-01, 7.1429795e-01, 7.1429795e-01,
       7.1429795e-01, 7.1429795e-01, 7.1429795e-01, 7.1429795e-01,
       7.1429795e-01, 7.1429795e-01, 7.1429795e-01, 7.1429795e-01,
       7.1429795e-01, 7.1429795e-01, 7.1429795e-01, 7.1429795e-01,
       7.1429795e-01, 7.1429795e-01, 7.1429795e-01, 7.1429795e

In [9]:
Y_test[0,:,1]

array([  1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1., 999., 999., 999.,
       999., 999., 999., 999., 999., 999., 999., 999., 999., 999., 999.,
       999., 999., 999., 999., 999., 999., 999., 999., 999., 999., 999.,
       999.])

In [10]:
np.min(np.nonzero(Y_test[0,:,1] == 999))

41

In [11]:
preds[0,0:41,1]

array([9.9999976e-01, 9.9999833e-01, 9.9999917e-01, 9.9999928e-01,
       9.9999499e-01, 9.9999928e-01, 9.9998915e-01, 9.9994969e-01,
       9.9559033e-01, 6.6094939e-04, 4.7267178e-05, 7.7620571e-06,
       4.1484614e-06, 2.1089227e-06, 9.6838585e-07, 2.8230340e-07,
       1.3917045e-07, 6.5984878e-08, 4.2399083e-08, 1.1210734e-07,
       2.1673502e-07, 2.6340032e-07, 3.9934702e-07, 2.9663005e-07,
       1.4983074e-07, 1.5193210e-07, 1.0938011e-07, 8.4359890e-08,
       7.1411120e-07, 7.2396060e-06, 9.5966425e-06, 8.0657287e-07,
       1.5958990e-01, 9.9994934e-01, 9.9999762e-01, 9.9999881e-01,
       9.9999952e-01, 9.9999952e-01, 9.9999988e-01, 9.9999928e-01,
       9.9999869e-01], dtype=float32)

In [13]:
np.where(preds[0,0:41,1] > 0.5, 1, 0)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
np.where(preds[0,0:41,1] > 0.5, 1, 0) - Y_test[0,0:41,1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])